### ISSUE TITLE
11.5 Emergency Response District

### ISSUE THREAD

**Issue by phomarkon** [SDU-Semester-Project-1-World-of-Zuul/SustainACityMAUI#1]
More about 11.5:
By 2030, significantly reduce the number of deaths and the number of people affected and substantially decrease the direct economic losses relative to global gross domestic product caused by disasters, including water-related disasters, with a focus on protecting the poor and people in vulnerable situations

Analysis: 
https://app.eraser.io/workspace/zV8YCgnIYGx3O0ssWHBQ

TLDR: 
District
**Emergency Response District** 
This district could have several emergency response stations such as fire stations, police stations, and hospitals. The player could work on improving response times, adding more resources, and organizing community safety workshops. 

**Crisis Management Game** 
The player could be tasked with managing a crisis such as a natural disaster, a disease outbreak, or a terrorist attack(maybe this is not a good idea). The game provides feedback on the effectiveness of the player's crisis management strategies, and the player could earn points for minimizing the impact of the crisis on the community. Also, the player can i.e. get scored based on time per decision.

**Tech Stack**
.NET 
MAUI
.NET ML/ Tensorflow.NET (optional, only if there is enough time)
Bogus (also optional) 

**Vision**
Implement ML to create a challenging and responsive game experience. Train a model based on the real data or generate a synthetic dataset. If I don't have time to implement it or the implementation of ML is obsolete because the mini-game is too simple. I'll follow the K.I.S.S. principle. Either way, I'll develop a simple algorithmic solution first before moving to the implementation of ML.

Roadmap:
1. Setup

- [x] Create a private repo
- [x] Finish analysis
- [x] Files structure 

2. Development Foundation

- [ ] Basic mini-game logic
- [ ] Finish 1 scenarios 
- [ ] Testing #1
- [ ] Merge to the MAUI

--- project is now usually finished ---

3. Start Machine Learning

- [ ] Select a framework
- [ ] Install dependencies
- [x] Get dataset or
- [ ] Generate dataset

4. Training

- [ ] Train the model

5. Testing

- [ ] Test the model

7. Merge (optional)

- [ ] Merge to the MAUI

**Comment by phomarkon** [comment]
Skipped the ML Implementation, .NET ML has no future and why predict the rain, if we know, there will be a disaster?
The final version is a simpler game than planned.  

- [x]  Done

**Comment by phomarkon** [comment]
- [x] Change the navigation back function.

**Comment by RespectMathias** [comment]
- [x] Change timer to dispatcher timer fix remove obsolete warnings
