### ISSUE TITLE
school minigame submit button (only half of it is visible)

### ISSUE THREAD

**Issue by KonyakB** [SDU-Semester-Project-1-World-of-Zuul/SustainACityMAUI#6]
<img width="1470" alt="Screenshot 2023-12-06 at 20 41 33" src="https://github.com/SDU-Semester-Project-1-World-of-Zuul/SustainACityMAUI/assets/144663007/c3fc15f2-aee8-47c0-827f-c405a0b204e0">

**Comment by RespectMathias** [comment]
Lazy fix, just nested it in a scroll view so now you can scroll down.
