### ISSUE TITLE
balancing act minigame placeholders

### ISSUE THREAD

**Issue by KonyakB** [SDU-Semester-Project-1-World-of-Zuul/SustainACityMAUI#7]
placeholders in textbox not displaying entirely
<img width="1470" alt="image" src="https://github.com/SDU-Semester-Project-1-World-of-Zuul/SustainACityMAUI/assets/144663007/2cd25fe9-132e-4d7b-ac53-f5df4480a52f">

**Comment by RespectMathias** [comment]
Are pickers now, you cannot choose wrong anymore. Meaning placeholders have been removed.
